# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "guardian-ai"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or
# malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Configure one of the supported pooler modes: `transaction`, `session`.
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: 0.0.0.0)
bind_address = "0.0.0.0"
# Port to use for the local Realtime API.
port = 54323
# Configure the JWT expiry for the anon key. Defaults to 3600 (1 hour), which cannot be more than
# 1 hour.
jwt_expiry = 3600
# Configure the refresh token expiry. Defaults to 60 days.
refresh_token_rotation_enabled = true
# Allow anonymous access to the realtime server. Defaults to false.
enable_anonymous_access = false

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1:54321"
# The default email template to use for sending emails. You can find the templates in
# supabase/templates/auth/email-templates.
email_template_dir = "supabase/templates/auth/email-templates"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 2500
# pop3_port = 1100

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/auth/email-templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending a confirmation message to the user's phone number.
template = "Your code is {{ .Code }} ."

# Use pre-defined map of phone number to OTP for testing.
# [auth.sms.test_otp]
# 4152127777 = "123456"

[auth.external.apple]
client_id = ""
enabled = false
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.azure]
client_id = ""
enabled = false
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.bitbucket]
client_id = ""
enabled = false
secret = ""

[auth.external.discord]
client_id = ""
enabled = false
secret = ""

[auth.external.facebook]
client_id = ""
enabled = false
secret = ""

[auth.external.github]
client_id = ""
enabled = false
secret = ""

[auth.external.gitlab]
client_id = ""
enabled = false
secret = ""

[auth.external.google]
client_id = ""
enabled = false
secret = ""

[auth.external.keycloak]
client_id = ""
enabled = false
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.linkedin]
client_id = ""
enabled = false
secret = ""

[auth.external.notion]
client_id = ""
enabled = false
secret = ""

[auth.external.slack]
client_id = ""
enabled = false
secret = ""

[auth.external.spotify]
client_id = ""
enabled = false
secret = ""

[auth.external.twitch]
client_id = ""
enabled = false
secret = ""

[auth.external.twitter]
client_id = ""
enabled = false
secret = ""

[auth.external.workos]
client_id = ""
enabled = false
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

[auth.external.zoom]
client_id = ""
enabled = false
secret = ""

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `slack`,
# `spotify`, `twitch`, `twitter`, `workos`, `zoom`.
[auth.external.custom]
client_id = ""
enabled = false
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio]
account_sid = ""
enabled = false
message_service_sid = ""
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

[auth.sms.messagebird]
access_key = ""
enabled = false

[auth.sms.textlocal]
api_key = ""
enabled = false

[auth.sms.vonage]
api_key = ""
api_secret = ""
enabled = false

# Configure one of the supported SMTP servers: `resend`, `sendgrid`, `mailgun`, `sendinblue`.
[auth.email.resend]
api_key = ""
enabled = false

[auth.email.sendgrid]
api_key = ""
enabled = false

[auth.email.mailgun]
api_key = ""
domain = ""
enabled = false

[auth.email.sendinblue]
api_key = ""
enabled = false

# Use an external SMTP server. The full list of providers are: `resend`, `sendgrid`, `mailgun`,
# `sendinblue`.
[auth.email.custom]
admin_email = ""
enabled = false
host = ""
pass = ""
port = 587
sender_name = ""
user = ""

# Configure one of the supported MFA providers: `totp`.
[auth.mfa.totp]
enabled = false
issuer = ""

# Configure one of the supported SSO providers: `saml`.
[auth.sso.saml]
enabled = false
# The public URL of your Supabase instance.
site_url = ""
# The entity ID of your Supabase instance.
entity_id = ""
# The private key used to sign the SAML request.
private_key = ""
# The certificate used to sign the SAML request.
certificate = ""
# The IDP metadata URL.
metadata_url = ""
# The IDP metadata XML.
metadata_xml = ""

[edge_runtime]
enabled = true
# Configure the port for the Edge Runtime API.
port = 54325
